[package]
name = "rust-spectrogram"
version = "0.1.0"
authors = ["Juhana Jauhiainen <juhana.jauhiainen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3"
wav = "0.4.1"
png = "0.16.7"

